Импорт библиотеки


In [1]:
import numpy as np

### 1. Докажите, что транспонирование транспонированной матрицы - это сама матрица: $(\mathbf{A}^\top)^\top = \mathbf{A}$.

In [6]:
A = np.arange(9).reshape(3, 3)
A_tt = (A.T).T
print(A)
print(A_tt)
np.array_equal(A, A_tt)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


True

### 2. Для двух матриц $\mathbf{A}$ и $\mathbf{B}$, покажите, что сумма и транспозиция коммутируют: $\mathbf{A}^\top + \mathbf{B}^\top = (\mathbf{A} + \mathbf{B})^\top$.

In [8]:
A = np.random.randint(1, 10, size=(3,3))
B = np.random.randint(1, 10, size=(3,3))
print(A.T + B.T)
print((A+B).T)
np.array_equal(A.T + B.T, (A+B).T)

[[10 13 10]
 [14 10  7]
 [16  9  9]]
[[10 13 10]
 [14 10  7]
 [16  9  9]]


True

### 3. Для любой квадратичной матрицы $\mathbf{A}$, сумма матриц $\mathbf{A} + \mathbf{A}^\top$ всегда ли симметрична? Можете ли вы доказать это, используя только предыдущие два упражнения?

In [9]:
A = np.random.randint(1, 10, size=(3,3))
print(A+A.T)
print((A+A.T).T)

np.array_equal(A+A.T, (A+A.T).T)

[[12 10 13]
 [10  6  8]
 [13  8  6]]
[[12 10 13]
 [10  6  8]
 [13  8  6]]


True

### 4. Мы определяли тензор `X` размерности (2, 3, 4). Что возвращает функция `len(X)`? Попробуйте записать ответ используя воображение, потом проверьте свой ответ в среде программирования. 

In [10]:
X = np.random.rand(2,3,4)
print(len(X))

2


### 5. Для тензора `X` произвольной размерности, всегда ли функция `len(X)` возвращает длину тензора по оси `X`? Что такое ось?

In [11]:
X = np.random.rand(1,2,3)
print(X.shape, ':', len(X))
X = np.random.rand(3,2,3,4)
print(X.shape, ':', len(X))
X = np.random.rand(5,4,2,1,4)
print(X.shape, ':', len(X))
X = np.random.rand(2,6,3,3,3,3)
print(X.shape, ':', len(X))
X = np.random.rand(4,5,1,2,3,4,1)
print(X.shape, ':', len(X))

(1, 2, 3) : 1
(3, 2, 3, 4) : 3
(5, 4, 2, 1, 4) : 5
(2, 6, 3, 3, 3, 3) : 2
(4, 5, 1, 2, 3, 4, 1) : 4


### 6. Запустите следующий фрагмент кода `A / A.sum(axis=1)` и проверьте полученный результат. Можете пояснить причину?

In [13]:
A = np.arange(9).reshape(3,3)
print(A)
print(A.sum(axis=1))

A / A.sum(axis=1)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 3 12 21]


array([[0.        , 0.08333333, 0.0952381 ],
       [1.        , 0.33333333, 0.23809524],
       [2.        , 0.58333333, 0.38095238]])

При делении массив сумм имеет неправильную форму, её нужно изменить

In [14]:
sum_correct = A.sum(axis=1).reshape(3, 1)
result = A / sum_correct
result

array([[0.        , 0.33333333, 0.66666667],
       [0.25      , 0.33333333, 0.41666667],
       [0.28571429, 0.33333333, 0.38095238]])

### 7. Рассмотрим тензор размерности (2, 3, 4). Какие размерности можно получить при суммирования элементов тензора по осям 0, 1 и 2?

In [15]:
X = np.random.rand(2,3,4)

print(X)
print(X.sum(axis=0).shape)
print(X.sum(axis=1).shape)
print(X.sum(axis=2).shape)

[[[0.75671584 0.55921681 0.76619685 0.99929092]
  [0.72432712 0.40204954 0.58957274 0.32034483]
  [0.4098178  0.43208792 0.35823349 0.35196886]]

 [[0.71032538 0.28555953 0.43696131 0.89364656]
  [0.23323222 0.24557325 0.7204394  0.92521673]
  [0.09838948 0.51921755 0.01656841 0.43868908]]]
(3, 4)
(2, 4)
(2, 3)


### 9. Передайте тензор с 3 или более осями в функцию `linalg.norm` и наблюдайте за его выводом. Что эта функция вычисляет для тензоров произвольной формы?

In [17]:
X = np.random.rand(1,2,3,4)

print(X)

np.linalg.norm(X)

[[[[0.09674696 0.24563991 0.9140795  0.11170627]
   [0.83686968 0.25278586 0.75137808 0.38232908]
   [0.60358174 0.39502471 0.03642683 0.80394616]]

  [[0.55058879 0.39412684 0.72630751 0.10313785]
   [0.98876971 0.0092901  0.39826174 0.10714583]
   [0.94712936 0.68713325 0.00701511 0.95298754]]]]


2.8253593563711754

Функция вычисляет форму Фробениуса для данного тензора

### 10. Определите 3 матрицы $\mathbf{A} \in \mathbb{R}^{2^{10} \times 2^{16}}$, $\mathbf{B} \in \mathbb{R}^{2^{16} \times 2^{5}}$ и $\mathbf{C} \in \mathbb{R}^{2^{5} \times 2^{14}}$, содержащие случайные переменные, распределенные по нормальному закону распределения. Вычислите произведение матриц: $\mathbf{A} \mathbf{B} \mathbf{C}$. Есть ли какая-либо разница в объеме памяти и скорости в зависимости от того, вычилсяете Вы $(\mathbf{A} \mathbf{B}) \mathbf{C}$ или $\mathbf{A} (\mathbf{B} \mathbf{C})$. Объясните результаты?

In [19]:
%load_ext memory_profiler

A = np.random.normal(0, 0.1, (2**10, 2**16))
B = np.random.normal(0, 0.1, (2**16, 2**5))
C = np.random.normal(0, 0.1, (2**5, 2**14))

In [20]:
%%timeit -n 1 -r 1
%%memit
A.dot(B).dot(C)

peak memory: 776.23 MiB, increment: 155.75 MiB
252 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [21]:
%%timeit -n 1 -r 1
%%memit
A.dot(B.dot(C))

peak memory: 9017.34 MiB, increment: 8368.82 MiB
13.7 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


Вычисление произведения в порядке A(BC) занимает значительно больше времени и памяти из-за большей размерности вычисляемых произведений (количество строк и столбцов в получаяющихся матрицах больше, чем в первом способе)

### 11. Определите 3 матрицы $\mathbf{A} \in \mathbb{R}^{2^{10} \times 2^{16}}$, $\mathbf{B} \in \mathbb{R}^{2^{16} \times 2^{5}}$ and $\mathbf{C} \in \mathbb{R}^{2^{5} \times 2^{16}}$. Есть ли какая-либо разница в объеме памяти и скорости в зависимости от того, вычисляете Вы $\mathbf{A} \mathbf{B}$ или $\mathbf{A} \mathbf{C}^\top$? Объясните результаты? Что изменится, если обозначить $\mathbf{C} = \mathbf{B}^\top$ без процедуры клонирования памяти? 

In [22]:
A = np.random.normal(0, 0.1, (2**10, 2**16))
B = np.random.normal(0, 0.1, (2**16, 2**5))
C = np.random.normal(0, 0.1, (2**5, 2**16))

In [30]:
%%timeit -n 1 -r 1
%%memit
A.dot(B)

peak memory: 709.55 MiB, increment: 0.00 MiB
1.57 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [29]:
%%timeit -n 1 -r 1
%%memit
A.dot(C.T)

peak memory: 709.55 MiB, increment: 0.00 MiB
863 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [31]:
%%timeit -n 1 -r 1
%%memit
A.dot(B.T.T)

peak memory: 709.55 MiB, increment: 0.00 MiB
831 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


Вычисление $\mathbf{A} \mathbf{B}$ занимает больше времени. Видимо, транспонированные матрицы обрабатываются быстрее при вычислениях. Если заменить C на B^T, то время так же снижается.

### 12. Определите 3 матрицы $\mathbf{A}, \mathbf{B}, \mathbf{C} \in \mathbb{R}^{100 \times 200}$. Сформируйте тензор с 3-мя осями путем объединения матриц $[\mathbf{A}, \mathbf{B}, \mathbf{C}]$. Какова размерность софрмирвоанного тензора? Вырежьте вторую координату третьей оси, чтобы восстановить $\mathbf{B}$. Проверьте, что ваш ответ правильный.

In [32]:
A = np.random.normal(0, 0.1, (100, 200))
B = np.random.normal(0, 0.1, (100, 200))
C = np.random.normal(0, 0.1, (100, 200))

tensor = np.stack([A, B, C], axis=0)
print(tensor.shape)

B_new = tensor[1,]
np.array_equal(B, B_new)

(3, 100, 200)


True